openapi: 3.2.0
info:
  description: '# flowable / flowəb(ə)l /


    - a compact and highly efficient workflow and Business Process Management (BPM) platform for developers, system admins and business users.'
  version: v1
  title: Flowable REST Manage History Process Instances API
  contact:
    name: Flowable
    url: http://www.flowable.org/
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: /flowable-rest/service
tags:
- name: Manage History Process Instances
paths:
  /history/historic-process-instances/delete:
    post:
      tags:
      - Manage History Process Instances
      summary: Post action request to delete a bulk of historic process instances
      description: ''
      operationId: bulkDeleteHistoricProcessInstances
      requestBody:
        $ref: '#/components/requestBodies/BulkDeleteInstancesRestActionRequest'
      responses:
        '204':
          description: Indicates the bulk of historic process instances was found and deleted. Response body is left empty intentionally.
        '404':
          description: Indicates at least one requested process instance was not found.
      security:
      - basicAuth: []
components:
  requestBodies:
    BulkDeleteInstancesRestActionRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BulkDeleteInstancesRestActionRequest'
  schemas:
    BulkDeleteInstancesRestActionRequest:
      type: object
      properties:
        action:
          type: string
        instanceIds:
          type: array
          items:
            type: string
        deleteReason:
          type: string
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
