openapi: 3.2.0
info:
  description: '# flowable / flowəb(ə)l /


    - a compact and highly efficient workflow and Business Process Management (BPM) platform for developers, system admins and business users.'
  version: v1
  title: Flowable DMN REST DMN Rule Service API
  contact:
    name: Flowable
    url: http://www.flowable.org/
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: /flowable-rest/dmn-api
tags:
- name: DMN Rule Service
paths:
  /dmn-rule/execute:
    post:
      tags:
      - DMN Rule Service
      summary: Execute a Decision
      description: ''
      operationId: execute
      requestBody:
        $ref: '#/components/requestBodies/DmnRuleServiceRequest'
      responses:
        '201':
          description: Indicates the Decision has been executed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DmnRuleServiceResponse'
      security:
      - basicAuth: []
  /dmn-rule/execute/single-result:
    post:
      tags:
      - DMN Rule Service
      summary: Execute a decision or a decision service expecting a single result
      description: ''
      operationId: executeWithSingleResult
      requestBody:
        $ref: '#/components/requestBodies/DmnRuleServiceRequest'
      responses:
        '201':
          description: Indicates the decision or decision service has been executed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DmnRuleServiceSingleResponse'
        '500':
          description: Indicates the decision or decision service returned multiple results
      security:
      - basicAuth: []
components:
  requestBodies:
    DmnRuleServiceRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DmnRuleServiceRequest'
      description: request
  schemas:
    DmnRuleServiceSingleResponse:
      type: object
      properties:
        resultVariables:
          type: array
          items:
            $ref: '#/components/schemas/EngineRestVariable'
        url:
          type: string
    DmnRuleServiceRequest:
      type: object
      properties:
        decisionKey:
          type: string
        tenantId:
          type: string
        parentDeploymentId:
          type: string
        inputVariables:
          type: array
          items:
            $ref: '#/components/schemas/EngineRestVariable'
        disableHistory:
          type: boolean
    EngineRestVariable:
      type: object
      properties:
        name:
          type: string
          example: myVariable
          description: Name of the variable
        type:
          type: string
          example: string
          description: Type of the variable.
        value:
          type: object
          example: test
          description: Value of the variable.
        valueUrl:
          type: string
          example: http://....
    DmnRuleServiceResponse:
      type: object
      properties:
        resultVariables:
          type: array
          items:
            type: array
            items:
              $ref: '#/components/schemas/EngineRestVariable'
        url:
          type: string
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
