openapi: 3.2.0
info:
  description: '# flowable / flowəb(ə)l /


    - a compact and highly efficient workflow and Business Process Management (BPM) platform for developers, system admins and business users.'
  version: v1
  title: Flowable CMMN REST Cmmn Engine API
  contact:
    name: Flowable
    url: http://www.flowable.org/
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: /flowable-rest/cmmn-api
tags:
- name: Cmmn Engine
paths:
  /cmmn-management/engine:
    get:
      tags:
      - Cmmn Engine
      summary: Get engine info
      description: ''
      operationId: getEngineInfo
      responses:
        '200':
          description: Indicates the engine info is returned.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EngineInfoResponse'
      security:
      - basicAuth: []
components:
  schemas:
    EngineInfoResponse:
      type: object
      properties:
        name:
          type: string
          example: default
        resourceUrl:
          type: string
          example: file://flowable/flowable.cfg.xml
        exception:
          type: string
          example: 'null'
        version:
          type: string
          example: 6.3.1
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
